/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InterfazDos;

/**
 *
 * @author Administrador
 */
public class VentanaDesigner extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaDesigner.class.getName());

    /**
     * Creates new form VentanaDesigner
     */
    public VentanaDesigner() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        lblValor = new javax.swing.JLabel();
        btnUNO = new javax.swing.JButton();
        btnDOS = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ventana Designer");
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        getContentPane().setLayout(null);

        panel.setLayout(null);

        lblValor.setText("----");
        panel.add(lblValor);
        lblValor.setBounds(30, 80, 80, 30);

        btnUNO.setText("UNO");
        btnUNO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUNOActionPerformed(evt);
            }
        });
        panel.add(btnUNO);
        btnUNO.setBounds(200, 30, 72, 23);

        btnDOS.setText("DOS");
        btnDOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDOSActionPerformed(evt);
            }
        });
        panel.add(btnDOS);
        btnDOS.setBounds(200, 110, 72, 23);

        getContentPane().add(panel);
        panel.setBounds(30, 30, 320, 240);

        setBounds(0, 0, 416, 309);
    }// </editor-fold>//GEN-END:initComponents

    private void btnUNOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUNOActionPerformed
        // TODO add your handling code here:
        this.lblValor.setText("UNO");
    }//GEN-LAST:event_btnUNOActionPerformed

    private void btnDOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDOSActionPerformed
        // TODO add your handling code here:
        this.lblValor.setText("DOS");
    }//GEN-LAST:event_btnDOSActionPerformed

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        // TODO add your handling code here:
        this.lblValor.setText("Se movio");
    }//GEN-LAST:event_formComponentResized

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaDesigner().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDOS;
    private javax.swing.JButton btnUNO;
    private javax.swing.JLabel lblValor;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
}
