/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ejercicio6;

import javax.swing.JOptionPane;

/**
 *
 * @author Administrador
 */
public class Ventana3 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Ventana3.class.getName());

    /**
     * Creates new form Ventana
     */
    public Ventana3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField2 = new javax.swing.JPasswordField();
        pwdControl = new javax.swing.JPasswordField();
        pwdVerificacion = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jPasswordField2.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ejercicio3");
        getContentPane().setLayout(null);

        pwdControl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwdControlActionPerformed(evt);
            }
        });
        getContentPane().add(pwdControl);
        pwdControl.setBounds(160, 80, 170, 40);
        getContentPane().add(pwdVerificacion);
        pwdVerificacion.setBounds(160, 140, 170, 40);

        jLabel1.setText("Verificacion");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 150, 100, 20);

        jLabel2.setText("Original");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 90, 100, 20);

        jButton1.setText("Verificar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(120, 220, 130, 40);

        setBounds(0, 0, 416, 309);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String pwdUno = pwdControl.getText();
        String pwdDos = pwdVerificacion.getText();
        
        if(pwdUno.equals(pwdDos)){
            JOptionPane.showMessageDialog(this, "Las contraseñás coinciden", "Verificacion", JOptionPane.INFORMATION_MESSAGE);
        }else{
             JOptionPane.showMessageDialog(this, "Las contraseñás NO coinciden", "Verificacion", JOptionPane.ERROR_MESSAGE);       
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void pwdControlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwdControlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwdControlActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Ventana3().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JPasswordField pwdControl;
    private javax.swing.JPasswordField pwdVerificacion;
    // End of variables declaration//GEN-END:variables
}
