/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ejercicio2;

import javax.swing.JOptionPane;

/**
 *
 * @author Administrador
 */
public class EjercicioDosVentana extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EjercicioDosVentana.class.getName());

    /**
     * Creates new form EjercicioDosVentana
     */
    public EjercicioDosVentana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCreador = new javax.swing.JButton();
        rdbRojo = new javax.swing.JRadioButton();
        rdbAzul = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ejercicio2");
        getContentPane().setLayout(null);

        btnCreador.setText("Datos Creador");
        btnCreador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreadorActionPerformed(evt);
            }
        });
        getContentPane().add(btnCreador);
        btnCreador.setBounds(90, 210, 220, 50);

        rdbRojo.setText("Rojo");
        getContentPane().add(rdbRojo);
        rdbRojo.setBounds(100, 70, 190, 50);

        rdbAzul.setText("Azul");
        rdbAzul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbAzulActionPerformed(evt);
            }
        });
        getContentPane().add(rdbAzul);
        rdbAzul.setBounds(110, 140, 170, 30);

        setBounds(0, 0, 416, 309);
    }// </editor-fold>//GEN-END:initComponents

    private void rdbAzulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbAzulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbAzulActionPerformed

    private void btnCreadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreadorActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Rodrigo Demarco", "Autor",JOptionPane.INFORMATION_MESSAGE);
        
        
    }//GEN-LAST:event_btnCreadorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new EjercicioDosVentana().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreador;
    private javax.swing.JRadioButton rdbAzul;
    private javax.swing.JRadioButton rdbRojo;
    // End of variables declaration//GEN-END:variables
}
