/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ejercicio5;

import java.util.ArrayList;

/**
 *
 * @author Administrador
 */
public class Ventana extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Ventana.class.getName());
    ArrayList<String> lista;

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
        lista = new ArrayList<>();
        lstValores.setListData(lista.toArray());
        btnCircunferencia.setSelected(true);
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lbl1 = new javax.swing.JLabel();
        txtRadio = new javax.swing.JTextField();
        btnCircunferencia = new javax.swing.JRadioButton();
        btnArea = new javax.swing.JRadioButton();
        btnCalcular = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtResultado = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstValores = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        lbl1.setText("Radio");
        jPanel1.add(lbl1);
        lbl1.setBounds(19, 24, 67, 26);
        jPanel1.add(txtRadio);
        txtRadio.setBounds(92, 26, 126, 22);

        grupo.add(btnCircunferencia);
        btnCircunferencia.setText("Circunferencia");
        jPanel1.add(btnCircunferencia);
        btnCircunferencia.setBounds(487, 18, 170, 21);

        grupo.add(btnArea);
        btnArea.setText("Area");
        jPanel1.add(btnArea);
        btnArea.setBounds(487, 45, 140, 21);

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        jPanel1.add(btnCalcular);
        btnCalcular.setBounds(19, 87, 100, 30);

        jLabel1.setText("Resultado");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(352, 90, 110, 16);
        jPanel1.add(txtResultado);
        txtResultado.setBounds(480, 87, 176, 22);

        jLabel2.setText("Valores Ingresados");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(19, 172, 180, 16);

        lstValores.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(lstValores);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(120, 220, 450, 146);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(60, 30, 840, 370);

        setBounds(0, 0, 1022, 463);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        // TODO add your handling code here:
        double resultado;
        int radio = Integer.parseInt(txtRadio.getText());
        
        if(btnCircunferencia.isSelected()){
            resultado = 2*Math.PI*radio;
            lista.add("Radio: "+radio+" Circunferencia: "+String.format("%.2f", resultado));        
        
        }else{
            resultado = Math.PI*Math.pow(radio,2);
            lista.add("Radio: "+radio+" Area: "+String.format("%.2f", resultado));        
        }
        txtResultado.setText(String.format("%.2f", resultado));   
        lstValores.setListData(lista.toArray());        
        
    }//GEN-LAST:event_btnCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Ventana().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnArea;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JRadioButton btnCircunferencia;
    private javax.swing.ButtonGroup grupo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl1;
    private javax.swing.JList lstValores;
    private javax.swing.JTextField txtRadio;
    private javax.swing.JTextField txtResultado;
    // End of variables declaration//GEN-END:variables
}
